### ISSUE TITLE
postInstallCommands not working

### ISSUE THREAD

**Issue by FIAV1** [gchq/gaffer-docker#178]
Hello, I tried to install this chart using `Helm 3.5.0` with custom values, but the `postInstallCommands` are never executed, since the pod responsible for that is never spawned. Here's my `values.yaml`:

```yaml
postInstallCommands:
  - hdfs dfs -mkdir /nifi
  - hdfs dfs -chown nifi /nifi
  - hdfs dfs -chmod 0755 /nifi
  - hdfs dfs -ls /

namenode:
  resources:
    limits:
      cpu: 1000m
      memory: 512M
    requests:
      cpu: 100m
      memory: 512M
  dataVolumes:
    count: 1
    pvcTemplateSpec:
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 10Gi

datanode:
  resources:
    limits:
      cpu: 1000m
      memory: 512M
    requests:
      cpu: 100m
      memory: 512M
  dataVolumes:
    pvcTemplateSpec:
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 10Gi

```
