### ISSUE TITLE
Improve version update script to exclude dependency versions

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-docker#52]
The version update script (./cd/updateAppVersion.sh) performs a find and replace on the Helm charts and app_version file. This is fine while we're on 0.x versions and the dependencies are all on versions greater than 0.x, however when the project matures and a version 1 is released there could be issues with conflicting versions (such as an app version getting updated accidentally). Improve the script's find and replace function so that only the versions that we want to update in the script are updated.

One idea is to use a comment on the lines that we want to use the script for:
```yaml
...
version: 0.5.0 # managed version
dependencies:
- name: zookeeper
  version: 2.1.1
```
Then only update the lines in Charts which have the `# managed version` comment
